            namelist / go / fmtout,maxstep,hrmax,dt0,dthr,hrpr,&
                      grad_in,glat_in,glon_in,&
                      fejer,&
                      rmin,rmax,&
                      altmin,&
                      fbar,f10p7,ap,&
                      year,day,mmass,&
                      nion1,nion2,hrinit,tvn0,tvexb0,ve01,&
                      gams,gamp,snn,stn,denmin,alt_crit,cqe